### ISSUE TITLE
This package name will be deprecated

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-AssemblyLineToolbox#8]
Ask @CaroRob which repo she worked on that uses the URL shortening code. Update the MAEvictionMoratorium code to the new name.

**Comment by nonprofittechy** [comment]
@plocket has some ideas on how to maintain this without breaking existing code. Another option:  just change those places manually.

**Comment by CaroRob** [comment]
Can I have a little more information about "the URL shortening code"? In what context did I use the URL shortening code, cause I can't remember what exactly  this is.
